name: Auto Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Set up SHH key and Deploy to Server
        uses: webfactory/ssh-agent@v0.9.0
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.HETZNER_USERNAME }}@${{ secrets.HETZNER_SSH_KEY }} << 'EOF'
            cd programs/read-the-bones
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
